# Generated by Django 5.2.7 on 2025-10-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='Nomor induk kependudukan')),
                ('nama_lengkap', models.CharField(max_length=100, verbose_name='Nama lengkap')),
                ('alamat', models.TextField(verbose_name='Alamat tinggal')),
                ('no_telepon', models.CharField(blank=True, max_length=15, verbose_name='nomer telepon')),
                ('tanggal_registrasi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
